image: maven:3.6.1

pipelines:
  branches:
    master:  # Trigger this for any pushes to the master branch.
      - step:
          name: Build and Deploy Snapshot Artifact
          trigger: automatic
          caches:
            - maven # Cache any dependencies we download, speeds up build times.
          script:
            - bash configure_maven.sh # Create our settings.xml file.  Will fail if environment variables aren't set properly.
            - mvn -B --file base-build/pom.xml verify # Ensure all artifacts build successfully before we attempt deploy in order to prevent partial deploys.
            - mvn -B --file base-build/pom.xml deploy # Now that all builds have completed, we can deploy all the artifacts.
